const carName = 'mazda';
let maxCarSpeed = '320';
let carOwner = 'Slavka';
alert(carName);
alert(maxCarSpeed);
alert(carOwner);
maxCarSpeed = '280';
console.log(maxCarSpeed);
maxCarSpeed = '240';
console.log(maxCarSpeed);
maxCarSpeed = '190';
console.log(maxCarSpeed);
carOwner = 'Slava';
console.log(carOwner);
carOwner = 'Slaventy';
console.log(carOwner);
carOwner = 'Vyacheslave';
console.log(carOwner);
